### ISSUE TITLE
Timesheet Display on first time and subsequent visits to Timesheet module.

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#57]
When you register a new user and login for the first time and click on the timesheets then the days do not appear.

![image](https://user-images.githubusercontent.com/2511712/28343344-c4251880-6c14-11e7-8fb3-da0145c46c01.png)

When I select the year then it all appears correctly.

This is really a feature rather than a bug but better if the a particular month&year can be show when the user clicks on the timesheet module.

Can the timesheet module do the following:

1. If the user is clicks on the timesheet module for the first time of a session then 

- display the first (oldest) monthly timesheet that requires updates (first red one). 
- otherwise (if none of previous exists) display first that is complete (and can be submitted)
- othewise, display current monthly timesheet.
(think that makes sense and covers the options).

1.  If the user has previously selected a particular month then display that same month when the user returns to the timesheet module (so they see the same as they had seen before just like a tab in chrome).
:+1: this functionality is already working.

**Comment by fergalddaly** [comment]
tested, working, closing.

**Comment by Keroberos** [comment]
I had to say, that there was a bug. Because of redirects and multiple navigation events component was initialize twice :( even data was loaded twice:
![image](https://user-images.githubusercontent.com/546027/28387213-7f99737c-6cce-11e7-84a5-1d8728f44736.png)

I've re-write this states saving logic and it should works fine now. Also saving state in BankAccount component is affected with this fix. 
Could you please take a look again on this? Sorry for that.

**Comment by fergalddaly** [comment]
I did notice that bank transactions were appearing twice.
I thought it was a completely separate issue.
But great that that is resolved with this fix.
I also noticed that the ordering was not right.
I'll have a look at that again now.

What was the issue on the timesheet as when I looked I thought it was working fine?

**Comment by fergalddaly** [comment]
Testing and passed.
Working very well and exactly to requirements in issue.
