### ISSUE TITLE
Email invoice - Client side

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#72]
Note: once this is configured and working, we can switch off the email element in just the same way as we have switched it off for registering the user.

## Requirements;
- when issuing an invoice provide an option to email to the agency's contact.
- support the option to email to self also.

## Entity change 
- add BillingEmail to the Agency entity
- Update the Agency table to include this.
- Update the Agency edit popup to include this.

## Client UI changes to Support the above.

When you click on issue show a dialog box with checkboxes:
- email to agency (agency@abc.com).
- email to self (self@self.com).

Note on dialog box:  I don't mind if this is a dialog box or something that is on the page itself.  Whatever you feel works best. 

By default both check boxes are switched on.
Show buttons on the right - cancel, send.

When both are switched off then disable the send both.
(as i think it is best if a copy of the invoice is emailed to self at least).

When the send button is pressed issue a call to the server to update the status to issued.

When the rest call returns with a result, show a message - email has been sent.
If a failure occurs then show a failure message.

note: to support the comms below between timesheet module and invoice module use events. an event is published when an timesheet is submitted and retracted.  Setup a listener on the invoice service to handle these events and set the days appropriately (not sure if this is done already or if the call is made directly).

- if the user retracts the timesheet  then the days on the invoice should is set to null (and other relevant values) and status is set to CREATED. Also set the HTML invoice to null (destroying previously generated version).  

- if an invoice has been already been issued then the timesheet can no longer be retracted - the status of the timesheet should be set to CLIENT_BILLED when the invoice is issued.  So a timesheet cannot be retracted once the status is CLIENT_BILLED or a subsequent status.

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/28755674-5659fb4a-7560-11e7-9c8a-1906b7957c75.png)

You can get fake lite SMTP server here: http://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=smtp4dev&DownloadId=269147&FileTime=129575689693530000&Build=21053

**Comment by Keroberos** [comment]
> note: to support the comms below between timesheet module and invoice module use events

Hi, Fergal! Do you meen client side or server side?
If you're talking about client side, then we don't need any events between modules, because when we're changing active module, the old one becomes disposed and it will be reloaded at the next activation.

If you want to minimize number of requests from the client to server we can add caching logic to the clients dataproviders

**Comment by fergalddaly** [comment]
Hi Vitalii,

I was talking about the server side not the client side.
Spring events.. as used for tasks.
I'm refactoring that part right now.

We do not need to consider performance and simply do what is best, the most logical approach - unless it is going to result in poor performance...

**Comment by Keroberos** [comment]
Ok, got it. I've configured SMTP server on heroku side, so I'll uncomment sending emails functionality

**Comment by Keroberos** [comment]
![image](https://user-images.githubusercontent.com/546027/28756300-f3b7c664-756b-11e7-8475-1bb54e6fbb5b.png)
Working on Heroku with real emails, but it's very slow

**Comment by Keroberos** [comment]
I've commited SMTP API key to the GIT in config files. Some spammers scans GITcommits  to find these keys and send spam using it :( That's why our account was blocked by SMTP server that I've used. So I've switched to another one and removed all security information from the config files to prevent incidents like that in the future https://github.com/Keroberos/sam/commit/8add98a930ac2bc1c438560681972efaacc4624e

You should get an email from Mailgun SMTP server with request "Would you like to receive emails from "Heroku Account" Mailgun account?"
Please approve it to be able to receive emails

**Comment by fergalddaly** [comment]
Thanks.  
Didn't see that mail but when I looked I noticed it.
I did add my own address to an earlier commit but I've removed it in the last one.
